### ISSUE TITLE
Problems with image recognition in the statistics window

### ISSUE THREAD

**Issue by Gersdorff** [Dejauxvue/AnnoCalculatorServer#11]
### TL/TR:

**English:**	
•	3840x2160 - massive problems, when recognizing the island names, at the latest after scrolling -> only partially resolvable / reproducible with complete restart of the game
•	All resolutions - General missing or incorrect island names of the New World and the Arctic
•	All resolutions - errors in the detection of coal in the 1st tab
• All resolutions - isolated problems with the detection of the houses, primarily 3840x2160
•	All resolutions - no recognition of Metropol's buildings in Tab 3

In the hope that the screenshot is in German, I will also share my problems / findings in German. Otherwise if I have to use the google translator.

**Deutsch:**
•	3840x2160 - Massive Probleme, bei der Erkennung der Inselnamen, spätestens nach scrollen -> nur mit Kompletten Neustart des Games bedingt lösbar /reproduzierbar
•	Alle Auflösungen - Generelle fehlende oder falscher Inselnamen der Neuen Welt und der Arktis
•	Alle Auflösungen - Fehler bei der Erkennung der Kohle im 1. Tab
•	Alle Auflösungen - Vereinzelte Probleme bei der Erkennung der Häuser, primär 3840x2160 betroffen
•	Alle Auflösungen – keine Erkennung der Gebäude von Metropol im Tab 3

Erstmal meinen Respekt an die Entwickler, die das hier vermutlich ihrer Freizeit zusammen bauen. ORC kann schon ganz schön triki sein, hatte mit sowas nur mal paar Versuche gemacht.

**Files:** [https://drive.google.com/open?id=1iyL2qKqRLbDDoJX6__xlm4EZI0Z3WKDG](https://drive.google.com/open?id=1iyL2qKqRLbDDoJX6__xlm4EZI0Z3WKDG)

**Inseln:**	
•	Die Alte Welt:	
	Alpha
	Beta
	Gamma – keine Bewohner
	Delta – keine Bewohner
	Epsilon
	Pig Farm – keine Bewohner
	The Second
•	Kap Trelawney:
	Metropol
•	Die Neue Welt: 
	New Alpha
	New Beta
	New Gamma
	New Delta
•	Die Arktis:
	King William Island

**Auflösung:** 3840x2160 nativ (Screenshot der Settings beigefügt)

### Vorgehensweise:

1. Spiel wird komplett neu gestartet, und Save Game geladen.
2. Statistik wird das erste Mal über die globale Bevölkerungsanzeige aufgerufen, womit der 4. Tab / Alle Inseln vorausgewählt ist.
3. Wichtig, es wurde und wird nicht gescrollt links in der Liste der Inseln
a.	Folgende Ergebnisse:

Insel | Fehler
--------|-------	
Alle Inseln | keine Fehler
Alpha | keine Fehler
Beta	|  Fehler bei der Zahl, der Häuser von den Bauern (142 statt 112), ggf. keine Hauserkennung mehr (siehe unten)
Delta - The Second 	| keine Fehler, ggf. keine Hauserkennung mehr
Metropol	| keine Fehler, ggf. keine Hauserkennung mehr
New Alpha | Fehler bei Inselname (genereller Fehler bei Inseln der neuen Welt), ggf. keine Hauserkennung mehr

4. Statistik wird wieder geschlossen, um sie erneut auf demselben weg zu öffnen, es wird wieder nicht gescrollt. Nur zur Kontrolle, Punkt kann auch übersprungen werden.
a.	Folgende Ergebnisse:	
•	Keine Grundsätzlichen Veränderungen zu oben
5.	Es wird gescrollt in der Inselliste: 
a.	Endposition wieder ganz oben:

Insel | Fehler
--------|-------	
Alle Inseln | Entdecker nicht erkannt
Alpha | Fehler bei Inselname
Beta - The Second | Fehler bei Inselname, ggf. keine Hauserkennung mehr
Metropol	| Fehler bei Inselname, ggf. keine Hauserkennung mehr
New Alpha | Fehler bei Inselname, ggf. keine Hauserkennung mehr

b.	Endposition nur eine Raste höher :

Insel | Fehler
--------|-------	
Alle Inseln | Entdecker nicht erkannt
Beta - The Second | ggf. keine Hauserkennung mehr
Metropol	| ggf. keine Hauserkennung mehr
New Alpha/New Beta | ggf. keine Hauserkennung mehr

c.	Endposition ganz unten:

Insel | Fehler
--------|-------
Alle Inseln | Entdecker nicht erkannt
Gamma – The Second |ggf. keine Hauserkennung mehr
Metropol	| ggf. keine Hauserkennung mehr
New Alpha - New Delta | Fehler bei Inselname, ggf. keine Hauserkennung mehr
King William Island	| Fehler bei Inselname (ist leer, ein eigener kürzer Name hatte keine Änderung zur folge), ggf. keine Hauserkennung mehr

6.	Fehler lässt sich nur durch kompletten Neustart des Spiels beheben. Ein Zurück zum Titelbild, und neu Laden ist nicht erfolgreich, es hat selben Effekt als ob schon gescrollt wurde.

7.	Es wurde nach Punkt 2 der 1. Tab ausgewählt:
a.	noch nicht gescrollt/ es wurde gescrollt:

Insel | Fehler
--------|-------
Alle Inseln | Entdecker nicht erkannt
Alpha - The Second |Fehler bei Inselname
Metropol	| Fehler bei Inselname
New Alpha | Fehler bei Inselname

b.	eine Raste höher:

Insel | Fehler
--------|-------
Alle Inseln | Entdecker nicht erkannt
Beta – The Second	| keine Fehler
Metropol	| keine Fehler
New Alpha/ New Beta | Fehler bei Inselname

c.	ganz unten:

Insel | Fehler
--------|-------
Alle Inseln | Entdecker nicht erkannt
Gamma – The Second | keine Fehler
New Alpha - New Delta |  Fehler Inselname
King William Island	| Fehler Inselname

8.	Es wurde nach Punkt 2 der 3. Tab und Einwohner ausgewählt:
a.	noch nicht gescrollt/ es wurde gescrollt:

Insel | Fehler
--------|-------
Alle Inseln | keine Fehler
Alpha – The Second | Fehler bei Inselname
Metropol	| Fehler bei Inselname, Bauern nicht Erkannt
New Alpha |  Fehler bei Inselname

b.	eine Raste höher:

Insel | Fehler
--------|-------
Alle Inseln | keine Fehler
Beta – The Second | keine Fehler
Metropol	| Fehler, Bauern nicht erkannt
New Alpha/ New Beta | Fehler bei Inselname

c.	ganz unten:

Insel | Fehler
--------|-------
Alle Inseln | keine Fehler
Gamma – The Second | keine Fehler
Metropol	| Fehler, Bauern nicht erkannt
New Alpha - New Delta | Fehler bei Inselname
King William Island	| Fehler bei Inselname, Bewohner nicht erkannt 

9.	Es wurde nach Punkt 2 der 3. Tab und Produktionsgebäude ausgewählt:
Sobald die Gebäudeliste scroll bar ist, wird das letzte Gebäude nicht erkannt
a.	noch nicht gescrollt/ es wurde gescrollt:

Insel | Fehler
--------|-------
Alle Inseln | keine weiteren Fehler
Alpha – The Second	 | Fehler bei Inselname
Metropol	| Fehler bei Inselname, Gebäude nicht erkannt
New Alpha | Fehler bei Inselname

b.	eine Raste höher:

Insel | Fehler
--------|-------
Alle Inseln | keine weiteren Fehler
Beta – The Second | keine weiteren Fehler
Metropol	| Gebäude nicht erkannt
New Alpha/ New Beta | Fehler bei Inselname

c.	ganz unten:

Insel | Fehler
--------|-------
Alle Inseln | keine weiteren Fehler
Gamma – The Second | keine weiteren Fehler
Metropol	| Gebäude nicht erkannt
New Alpha - New Delta | Fehler bei Inselname
King William Island	| Fehler bei Inselname, Gebäude nicht erkannt 

Beim späteren Vergleich der Screenshots ist mir mindestens eine Veränderung bei den Bildern vor und nach dem Scrollen aufgefallen. Dieser ist am Ende der Inselliste zu finden, hier ist auf einmal ein wenig mehr zusehen als vorher.

**Weiterer Fehler ggf. keine Hauserkennung mehr:**	
Zusätzlich zum verhalten wie oben auf geführt, kommt noch hinzu. Das bei direkter Auswahl nach Erstaufruf der Statistik (kein scrollen) Beta beliebig oft ohne Fehler (außer der Zahlenfehler) erkannt wird. Ein schließen und erneutes öffnen der Statistik mit direkter wieder Auswahl hat keinen Einfluss auf das Ergebnis. Wählt man jedoch andere Inseln zum Auslesen aus, und lässt diese Auslesen, kommt es zu einem Fehler über kurz oder lang. Bei Beta werden die Häuser nicht mehr erkannt, was ab dann auch für alle Nachfolgenden Inseln gilt, und so auch bleibt. Die Häuser von Alle Inseln bzw. Alpha werden immer erkannt. 
Beim Vergleich der Screenshots, ist mir eine Veränderung in der Titelleiste aufgefallen, was wohl der Grund für das nicht erkennen sein wird.

**Fazit:**
Nach dem Scrollen in der Liste der Inseln, wird fast immer teile der Beschriftung Die Alte Welt oder Die Neue Welt als Inselname erkannt. Durch das weg scrollen der Beschriftung Die Alte Welt, klappt die Erkennung der Namen für Insel der Alten Welt bzw. des Kaps. Inseln der Neuen Welt bzw. der Arktis werden generell falsch erkannt. Wobei selbst die verschiedenen Tabs schon unterschiedliche anfangs Ergebnisse liefern. Auch werden oft Häuser / Bewohner nicht richtig erkannt. Ich vermute, das hier Begrenzungsmarkierungen nicht mehr erkannt werden. Bzw. die nicht Erkennung der Häuser scheint im 4. Tab meist auf das Problem bei Beta zurück zu führen zu sein.

Keine Ahnung ob es nicht Sinn macht bzw. einfacher wäre den Inselnamen aus der oberen Mitte zur Erkennung zu nutzen, der Kontrast sollte denke ich dazu ausreichen. Die Change die ich darin sehe, ist die immer gleiche Position, auch bei Tab / Insel-wechseln, kein sich verändernder Hintergrund soweit ich das sehe. Man könnte dann auch problemlos durch die Inselliste scrollen, da man nicht mehr auf die Erkennung der Blau hinterlegten Inselbezeichnung angewiesen ist, die man ja auch einfach wegscrollen kann.

**Fehler Kohle:**
Durch Zufall ist mir dabei auch aufgefallen, daß die Bilderkennung Probleme mit der Kohle im 1. Tab hat, in der Liste als auch im Filter, dieses Betrifft alle Auflösungen.

Wird falsch erkannt als:
•	Wahlweise als Rumbrennerei/ Robbenfängerei
•	Blau hinterlegt wahlweise als Schokoladenfabrik/ Stahlwerk
Zeilen die durch die Maus hervorgehoben werden, werden offensichtlich generell nicht erkannt im 1. Tab.

### Andere Auflösungen:
Tests mit anderen Auflösungen habe ich auch zum Vergleich durchgeführt, hier traten meist die gleichen Fehler auf.

**1920x1080**
•	Inselnamen fehlerhaft, nach wieder hochscrollen
•	Inselnamen der Neuen Welt bzw. der Arktis generell fehlerhaft
•	Vereinzelt Fehler bei der Erkennung Gebäuden/ Bewohnern. 
	Hier sind besonders die letzten Bewohner in der der Gesamtliste (Tab 4), bzw. Metropol betroffen (Tab 3)
•	Letztes Produktionsgebäude wird nicht Erkannt im Tab 3
•	Fehler mit Kohlerkennung im Tab 1

**2560x1440**
•	Inselnamen der Neuen Welt bzw. der Arktis generell fehlerhaft
•	Inselname Pig Farm wird nach wieder hochscrollen nicht erkannt im Tab 1 bzw. 3
•	Vereinzelt Fehler bei der Erkennung Häuser/ Bewohnern
	Tab 4 / Beta -> Zahl der Bauernhäuser falsch (12 statt 112)
	Tab 4 / Alle Inseln -> Letzen Bewohner in der Liste werden meist nicht erkannt, durch scrollen bzw. mit der Maus über die Titelleiste bewegen, kommt es dort zu Veränderungen, was sich auf die Erkennung der Bewohner offensichtlich auswirkt
	Tab 3 / Metropol wieder besonders betroffen
•	Letztes Produktionsgebäude wird nicht Erkannt im Tab 3
•	Im Tab 1 wir hin und wieder auch das letzte Feld nicht erkannt
•	Fehler mit Kohlerkennung im Tab 1

Sollten bestimmte Screenshots benötigt werden, so bitte einfach melden.

Denn schon mal danke im Voraus, denn das ist ja doch ein ganzer haufen.

**Comment by NiHoel** [comment]
Danke für den ausführlichen Fehlerbericht, es wird etwas dauern bis ich alles im Detail durchgesehen habe. Kannst du mir auch dein Savegame zukommen lassen, damit ich Fixes auch live testen kann?

**Comment by Gersdorff** [comment]
Habe den Save, dem Speicherort der anderen Dateien hinzugefügt.

**Comment by NiHoel** [comment]
Wenn du willst kannst du schon folgende Zwischenversion ausprobieren (Häuser- und Inselnamenerkennung sollten besser sein)

[ServerD.zip](https://github.com/Dejauxvue/AnnoCalculatorServer/files/3963907/ServerD.zip)

**Comment by NiHoel** [comment]
Falls du noch Lust und Zeit hast, kannst du mich beim (Unit-)Testen unterstützen.

0. Klone das Repository.
1. Speichere hierfür Screenshots (korrekt und nicht korrekt erkannte) unter assets/image_recon/test_screenshots ab (z.B. ScreenshotXY.png).
2. Öffne cpp/visual studio/Calculator Server/server/debug_main.cpp (ein Texteditor genügt)
3. Füge unter unit_tests einen weiteren Block hinzu:
   1. Bild laden: image_recog.update("german", image_recognition::load_image("image_recon/test_screenshots/ScreenshotXY.png"));
   2. Erkennung durchführen durch Aufruf folgender Methoden (es genügt nur das Auszulesen, was auch tatsächlich dargestellt wird):
      1. Anzahl Einwohner (Statistikmenü oder HUD): get_population_amount()
      2. Anzahl Häuser (Finanzen oder Bevölkerung): get_assets_existing_buildings()
      3. Anzahl Fabriken: get_assets_existing_buildings()
      4. Produktivität (als ganze Prozentzahl, d.h. 100% werden als 100 zurückgegeben): get_average_productivities()
      5. Inselname: get_selected_island()
   3. Validieren der Rückgabe: Als Schlüssel wird immer die spielinterne GUID verwendet; wichtig: Zeilen, die nicht oder nicht mindestens zu 90% zu sehen sind, bitte von der Überprüfung ausschließen
      1. Bevölkerung:  15000000 bis 15000006 = Bauern bis Obreros; 112642 = Erkunder; 112643 = Techniker
      2. Waren / Fabriken: Bei Icons und Text, selbst wenn er sich auf Produktnamen bezieht, wird immer die (erst beste) Fabrik genommen; d.h. öffne assets/texts/params_2019-12-10_iconnames.json mit Texteditor und suche nach Fabriknamen -> scrolle nach oben bis du "guid" siehst (darüber sollte stets "name" und der interne Name der Fabrik stehen); z. B. Schlittenfabrik läuft auf 150% -> suche guid: 112681 -> trage BOOST_ASSERT(result.at(112681 ) == 150); ein.
5. Commit und Push der Änderungen

**Comment by Gersdorff** [comment]
Wollte den mal die andere ServerD.exe ausprobieren, bekomme aber beim Ausführen die Fehlermeldung das er 4 dll´s nicht finden kann. Denn geh doch richtig in der Annahme, das sie ins selbe Verzeichnis wie die alte muß.

- opencv_imgcodecs343d.dll
- cpprest_2_10d.dll
- opencv_core343d.dll
- boost_filesystem-vc142-mt-gd-x64-1_70.dll

Die 4 dlls sind bis auf das gd bzw d im namen vorhanden, diese kopieren und umbenennen, brachte in sofern etwas, das darauf weitere dll fehlen.

- MSVCP140D.dll
- opencv_imgproc343d.dll
- VCOMP140D.dll
- VCRUNTIME140D.dll
- VCRUNTIME140_1D.dll

Die opencv_imgproc343.dll könnte ich noch mal kopieren und umbenennen aber die anderen habe ich nicht. Auch ist die exe von ca. 2.5 auf über 9 MB angewachsen.

**Comment by NiHoel** [comment]
Hier ein weiteres Update (bitte wieder in das alte Verzeichnis - so wie du es von Release 2.0 hast)
[Release.zip](https://github.com/Dejauxvue/AnnoCalculatorServer/files/3964311/Release.zip)

**Comment by NiHoel** [comment]
Test if the new release fixes all the issues. If so, close this issue.

**Comment by Gersdorff** [comment]
### Ergebnisse:

**Alle Auflösungen**
- Die Anwendung schließt sich, wenn im Tab 4 keine Bewohner aufgeführt werden, wie zBsp. bei der Insel Delta.
- Tab 3 wenn Liste runtergescrollt ist, wird generell letztes Gebäude nicht erkannt, liegt hier wohl an dem dünnen hellen Streifen der oben bzw. unten bei der Liste ist.
- bei Tests zusammen mit der Calculator Seite, ist mir nur noch aufgefallen das paar Gebäude auf unterschieliche Welten gelegt werden
a. Holzfäller, Ziegel -> neue Welt
b. Sägewerk, Lehmgrube -> alte Welt
c. Köhlerei -> Arktis

Zumin Holz und Ziegel sollten auf eine Welt gelegt werden, hier wäre die Alte Welt wohl die beste Wahl, sofern du nicht noch was einbauen willst, was erkennt in welcher Welt sich die Insel befindet.

**3840x2160**
- Tab 1 wenn Liste runtergescrollt ist, wird jedes ca. 2-3 mal das letzte Gebäude nicht erkannt, was aber durch 1 sec poll den die HP macht, nicht weiter auffallen würde

**2560x1440**
- Tab 1 wenn Liste runter gescrollt ist, wird das letztes Gebäude generell nicht erkannt

**1920x1080**
- keine weiteren Fehler

Keine Ahnung ob das gewollt ist das die ServerD.exe keine Bilder mehr im Ordner Ablegt.

**Comment by NiHoel** [comment]
> 
    Die Anwendung schließt sich, wenn im Tab 4 keine Bewohner aufgeführt werden, wie zBsp. bei der Insel Delta.

Gelöst, kommt mit nächstem Update.

    Tab 3 wenn Liste runtergescrollt ist, wird generell letztes Gebäude nicht erkannt, liegt hier wohl an dem dünnen hellen Streifen der oben bzw. unten bei der Liste ist.

Bekannt, ich lasse aber lieber die strengen Einstellungen, bevor noch ein falsches Icon erkannt wird. Umsortieren, dann steht es woanders und man kann es erfassen.

    bei Tests zusammen mit der Calculator Seite, ist mir nur noch aufgefallen das paar Gebäude auf unterschieliche Welten gelegt werden
    a. Holzfäller, Ziegel -> neue Welt
    b. Sägewerk, Lehmgrube -> alte Welt
    c. Köhlerei -> Arktis

    Zumin Holz und Ziegel sollten auf eine Welt gelegt werden, hier wäre die Alte Welt wohl die beste Wahl, sofern du nicht noch was einbauen willst, was erkennt in welcher Welt sich die Insel befindet.

Grundsätzlich sollte es vor allem auch bei Allen Inseln funktionieren, da erhalte ich aber in der Finanzansicht (wenn nicht ausgeklappt) keinerlei Infos, in welcher Region es sich befindet. Außerdem wird z.B. das Sägewerk mehrfach aufgeführt (für jede Region einmal). Falls dir eine elegante Lösung einfällt, immer her damit.

     Keine Ahnung ob das gewollt ist das die ServerD.exe keine Bilder mehr im Ordner Ablegt.

Ich habe die Projektstruktur aufgeräumt, ab jetzt werden Testbilder in debug_images abgelegt, allerdings muss der Ordner zuvor manuell erstellt werden.

**Comment by Gersdorff** [comment]
das trennt er ja leider gerade auch bei Alle Inseln, deswegen ja mein Vorschlag das denn eben immer in die Alte Welt zu packen

![ids](https://user-images.githubusercontent.com/58783912/70866897-7e5bd580-1f6f-11ea-9a0c-444cafbe2fbc.JPG)
![bild1](https://user-images.githubusercontent.com/58783912/70866898-80be2f80-1f6f-11ea-8959-3562a8dc6a5c.JPG)
![screenshot](https://user-images.githubusercontent.com/58783912/70866899-8287f300-1f6f-11ea-8bce-285eb37476c0.png)

**Comment by Gersdorff** [comment]
Was mir alternativ, dazu nur einfällt, ist wieder anzufangen, die Inselnamen wieder links von der Liste abzugreifen, und denn das Icon vor dem Namen auszuwerten. Nur hast denn wieder die probleme die es vorher gab.

Da scheint mir das einfachste zusein, eben nur die ID´s für eine Welt bei solchen Gebäude die es in mehreren Welten gibt zurück zugeben.

Und dann würde ich wahrscheinlich eher was machen, das man im Kalkulator was festlegen kann, zu welcher Region die Insel gehört. Nur keine Ahnung wie aufwenig das denn wieder wird.

**Comment by NiHoel** [comment]
Ich favorisiere folgende Lösung (leider sehr aufwändig umzusetzen):

1. Da sich Produktivität auf ein Produkt bezieht, wird die Produktivität aller Gebäude, die dieses Produkt herstellen geupdated.
2. Alle Inseln: Bei mehrdeutigen Gebäuden (z. B. Holzfäller) müssen in der Finanzansicht die Einzelgebäude ausgeklappt sein -> Region kann ausgelesen werden -> eindeutige Zuordnung
3. Eine Insel: Aus linker Liste wird Zuordnung Insel-Region gespeichert -> eindeutiges Auflösen des Fabriknamens möglich
4. (optional) optimale Produktivität auslesen (aus rechtem Panel der Produktionsübersicht)
