### ISSUE TITLE
vcruntime140_1.dll missing

### ISSUE THREAD

**Issue by FotoScout24** [Dejauxvue/AnnoCalculatorServer#13]

**Comment by NiHoel** [comment]
You have to download and install the microsoft redist package: https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by Kasta2701** [comment]
thank you, now it runs perfect

**Comment by FotoScout24** [comment]
correct .. now it runs (at least once during a game). Was it written somewhere that this package is required? It seems I missed it .. thank you anyway.. great tool. Better than what I’ve seen before..
