### ISSUE TITLE
[Idea] Add item recognition

### ISSUE THREAD

**Issue by auipga** [Dejauxvue/AnnoCalculatorServer#15]
I don't know what this program is capable of.
Can you also recognize images and find out which items someone has in the warehouse or in a trade union?
(I know that some items share identical icons. They would need to be handled manually.)

**Comment by NiHoel** [comment]
In principle, yes:
1. Create a json file with icon guid, icon name and background name (= rarity)
2. get spots (relative to screen) where item lists are visible
3. detect whether such a spot is open (trade union /warehouse menu open, item list under trade union in finance tab expanded, ...)
4. get the precise cells where items are 
5. match against all template images (filter based on rarity might be possible)
6. get the context of the item, i.e. on which island, in which warehouse (consider that there might be several indistinguishable trade unions containing different items on the same island but at one moment only one or a few of them are visible -> think about how you want to handle this)
7. return result, maybe a list of guids if icon is ambiguous

Biggest caveat: recognition accuracy (tightly coupled to getting to getting the precise spot of an icon)
the rest is doable, but requires quite some work.

Just to keep in mind: The program only works on screenshots (does NOT look into the game's memory) -> can only detect what is well visible
