### ISSUE TITLE
Server.exe and ServerD.exe close after Language recieved 

### ISSUE THREAD

**Issue by StingMcRay** [Dejauxvue/AnnoCalculatorServer#16]
Version 2.1.1
![afbeelding](https://user-images.githubusercontent.com/18048706/71359504-ea03fb00-258c-11ea-8ab4-7b7d6e807561.png)

This is the only thing i get and then it close
Have open : Anno 1800 (no trainers, no mods) and the Local Website

Also i see double DLL versions of different files : (do not know of that is intentionally)  
![afbeelding](https://user-images.githubusercontent.com/18048706/71359611-5121af80-258d-11ea-9549-86cc6a3a53c9.png)

Running Windows 10 64bits
Mozilla Firefox 71.0 (64bits)

**Comment by tompauwaert** [comment]
Same issue. Using Chrome Version 79.0.3945.88 (Official Build) (64-bit)

**Comment by NiHoel** [comment]
Together with @StingMcRay  we found out that this is caused by an IllegalInstructionException which occurs when binary code is incompatible.
But I still don't know why it happens: Issues in the newly build dependent libraries or Visual Studio Settings?
