### ISSUE TITLE
Wrong resolution detected

### ISSUE THREAD

**Issue by Moepchi** [Dejauxvue/AnnoCalculatorServer#17]
The server always detects the wrong resolution for me.

Log:
detected resolution: 2560x1440

but my game runs with a resolution of 3840x2160 in fullscreen.

Whats wrong and what can i do so that it works?

Thx for your help. :)

**Comment by NiHoel** [comment]
1. Change the mode to full screen windowed
2. Create a folder debug_images next to ServerD.exe; run ServerD.exe; make sure the game is open, focused and requests are received; close ServerD.exe; send me debug_images/screenshot.png

**Comment by Moepchi** [comment]
Hi, thx for your answer. The game runs in fullscreen windowed but it dosn't work. :'(

Here you have the screenshoot.png picture from the debug_images folder:
![screenshot](https://user-images.githubusercontent.com/20614698/72140350-da5c2300-3390-11ea-807c-ca3e57ed8dd1.png)

**Comment by NiHoel** [comment]
The screenshot function does not capture the whole game. Do you have similiar issues when using external tools (in-game screenshot, external snipping tool)?

**Comment by Moepchi** [comment]
I have a 3 monitor setup.  Maybe that's the problem? No, I have no problems with other programs that can take screenshots.

**Comment by NiHoel** [comment]
I know from other users that normally a resolution of 3840x2160 works. Currently, I have no idea why - in your case - screenshotting only captures a fraction of the actual game. 

Can you try it on a different monitor / different resoultion?

**Comment by Moepchi** [comment]
I tried a resolution from 1920x1080 in fullscreen windowed but the server detects a resolution of 1280x720

here you have a screenshot:

<img width="1082" alt="Unbenannt" src="https://user-images.githubusercontent.com/20614698/72149017-74789700-33a2-11ea-9b34-57e95ff7598d.PNG">

Perhaps it is because 2 out of 3 monitors are in FullHD and the other one on which the game is running is in UHD

**Comment by NiHoel** [comment]
Does Anno run in a virtual machine?
Doe use any graphic card settings that may lead to differences between rendered and displayed window size (e.g., down / up scaling)?
Any scaling options in windows enabled?

**Comment by Moepchi** [comment]
No, it runs on my local machine. Not that I know but I can look it up again.

**Comment by Moepchi** [comment]
Ok, i have found the problem. The scaling in windows was set to 150%. After i have deactivated this, it works but is there a way that i can leave it active?

**Comment by NiHoel** [comment]
There is a workaround you can try: Create and open a folder "Anno 1800" (only the name of that window matters + it fills the screen on which you play Anno) -> leave it open when starting Anno and the server -> the server will complain that it found multiple windows with the name "Anno 1800" (ignore this warning) -> the statistics screen should work fine, perhaps there is still a warning "failed to load ..." and the height of the detected resoultion is a bit less than the actual height. In that case copy & rename the folder "image_recon/3840x2160" to the new values.

Run ServerD.exe and open "debug_images/screenshot.png" to verify that the whole game is captured.
