### ISSUE TITLE
Server issue

### ISSUE THREAD

**Issue by kro3ger** [Dejauxvue/AnnoCalculatorServer#18]
Hi
So, i have this problem, i don't understand why. My game resolution is 1920x1080.
Maybe someone can help me 
thx

![erreur_server](https://user-images.githubusercontent.com/62185111/76687663-6d7e3700-6626-11ea-9620-3cc172935ac1.png)

**Comment by NiHoel** [comment]
You can try Options -> Graphics -> Fullscreen Windowed

If that doesn't help, can you create a folder "debug_images" where ServerD.exe is located, run ServerD.exe and send me "debug_images/screenshot.png"?

**Comment by kro3ger** [comment]
The change of resolution doesn't work.
That's the file you ask 
![screenshot](https://user-images.githubusercontent.com/62185111/76703170-f1d8c480-66cf-11ea-944f-4890ea88bb99.png)

**Comment by NiHoel** [comment]
Did you make sure that Anno is not covered by the console?
Does screenshot.png always show the console?
Does detected resolution change when you resize the console window?

Normally, screenshot.png should show a screenshot of the Anno game.

**Comment by kro3ger** [comment]
![screenshot](https://user-images.githubusercontent.com/62185111/76705006-112a1e80-66dd-11ea-8c66-7a45812e84b6.png)
ok screenshot.png screens this

**Comment by NiHoel** [comment]
Ok, this makes more sense.
If you use scaling in Windows, reset it to 100%, see 
https://github.com/Dejauxvue/AnnoCalculatorServer/issues/17#issuecomment-573164862

**Comment by kro3ger** [comment]
ok thx, thats good now
