### ISSUE TITLE
Artisans Island Population not send to local web

### ISSUE THREAD

**Issue by StingMcRay** [Dejauxvue/AnnoCalculatorServer#3]
Dear devs

On version 1.1.3 the artisans count ill not send to the local website is you use the Island Population, on Global Population it works fine : 
![afbeelding](https://user-images.githubusercontent.com/18048706/63649974-f98d4780-c744-11e9-8cf3-f242fc0407d8.png)

(on version .1.1.2 it is working fine)

**Comment by Dejauxvue** [comment]
Hi
Thanks for your Feedback, I'm looking Into this
You probably have to wait until next week for a new release, I don't have access to a pc right now

**Comment by StingMcRay** [comment]
Sorry : But also on 1.1.2 i have issues as it comes to Artisans on Island Populations check
on the Global Population it works  
![afbeelding](https://user-images.githubusercontent.com/18048706/63652867-965fdd00-c765-11e9-938a-0333a4447cd5.png)

**Comment by Dejauxvue** [comment]
Could you post a Screenshot of the game while viewing Island population?

**Comment by StingMcRay** [comment]
No problem, *i and the rest will wait :)*
Btw : When you reach the Engineers the info of the Island Population will go to the local web again,

**Comment by StingMcRay** [comment]
Update: After a retest of this issue i noticed the following : 
When i start anno firs (incl. continue), then the serverd.exe and then the local website the artisans are perfect counted, 
However my wife (on version 1.1.2) has discovers that when the Tier 1 New World (Jornaleros) reach 1000+ then only the first 3 numbers (in this case 100) will seen as counted population : i will test this also to see what happens on  1.1.3

**Comment by StingMcRay** [comment]
I will close this one, and made a new one with the final results
