### ISSUE TITLE
Server doesn't work with new update

### ISSUE THREAD

**Issue by Electroblade** [Dejauxvue/AnnoCalculatorServer#5]
After Botanica update the server does not work, no auto update of the calculator

**Comment by Dejauxvue** [comment]
Hi
I will be looking into this tomorrow.
Could you provide further information like:
- a non-compressed screenshot of the game while the bug occurs
- the output from the console window while the bug occurs
- use ServerD.exe instead of Server.exe; reproduce the bug; and post the images that lie direclty(!) in image_recon (no subfolders)
These help a lot when fixing bugs of this kind :)
Thanks for you interest in this project

**Comment by Electroblade** [comment]
Here you go.
There is no image directly in image_recon only the one in the resolution folder. 1920x1080
![calculator](https://user-images.githubusercontent.com/54334325/64917701-476cfc80-d793-11e9-9fe6-2136d728632a.JPG)
![screenshot_2019-09-15-08-13-47](https://user-images.githubusercontent.com/54334325/64917705-5489eb80-d793-11e9-9c0c-abc5affa0f42.jpg)
![screenshot_2019-09-15-08-17-52](https://user-images.githubusercontent.com/54334325/64917706-581d7280-d793-11e9-9e31-3e1d464995fd.jpg)
![screenshot_2019-09-15-08-18-06](https://user-images.githubusercontent.com/54334325/64917707-59e73600-d793-11e9-95ce-82dddd5b9516.jpg)
[ServerD_Console.txt](https://github.com/Dejauxvue/AnnoCalculatorServer/files/3613455/ServerD_Console.txt)

**Comment by EchtkPvL** [comment]
The window-name changed:
```
00000000000A0CC6:  Anno 1800
match result 0
```
![2019-09-15_151445 b5448](https://user-images.githubusercontent.com/10640811/64922104-9898e280-d7cb-11e9-93fa-14257fce4c0d.png)

**Comment by Electroblade** [comment]
Thought it might have been as the server was trying to find Anno 7. 

Is there a way for me to change it on my side or do I have to wait on a new version of the server?

**Comment by DaJp1337** [comment]
Changing the window name from Anno 7. to Anno 1800 does indeed fix the problem!

I did fork the project and requested pull.

The problem should be solved soon, I hope!

**Comment by Electroblade** [comment]
Thanks

**Comment by Dejauxvue** [comment]
thanks for all the advice.
The new releaese (v1.1.4) should fix the Problem
