### ISSUE TITLE
A silence mode when failing to load population symbol

### ISSUE THREAD

**Issue by StingMcRay** [Dejauxvue/AnnoCalculatorServer#7]
Hy there : i have a question ; 
If this happens : 
![afbeelding](https://user-images.githubusercontent.com/18048706/69965860-76367b80-1515-11ea-98ae-37974f127dbb.png)
Can you not build in a Silence mode then, till he find it again, and maybe a message like  
"Select the game Anno 1800 to Proceed" (or something like that)

Because when you hovering over the games Population Symbol, but you do not have selected the game, if will not work, a message should tell the user that the game itself is still not selected

(This occurs when you select an other app *on an other screen or same screen*)

Kindly regards
Sting McRay

**Comment by NiHoel** [comment]
We will do a major update after the release of Game Update 6 - then the server will read the values from the statistics screen.

We will incorporate your feedback and provide appropriate console messages.
