### ISSUE TITLE
Some noticeable things : Server > Website

### ISSUE THREAD

**Issue by StingMcRay** [Dejauxvue/AnnoCalculatorServer#8]
Dear Devs,

There are a view things that get annoying from game to server to website : 
First of all, if i have not add my island name in to the web site, and i hover over my island inhabitants the numbers will not put on the site, even when i have  switched off the "Restrict updates to the selected island"
![afbeelding](https://user-images.githubusercontent.com/18048706/70606561-069f4b00-1bfd-11ea-9627-0e3893890098.png)
is it possible that the server act as before, like i would choice what i want to view ether the overall inhabitants or island inhabitants without creating my islands name into the website.

Next thing that buggers me, is when i open the Statics window > inhabitants, the website goes to houses count ("Input number of houses instead of residents") while i have not select that option. The website or the server switched it on while i not want that!
![afbeelding](https://user-images.githubusercontent.com/18048706/70606861-ad83e700-1bfd-11ea-804a-51b7a9921c9d.png)
Hope this can be fixed

Kindly Regards

**Comment by NiHoel** [comment]
Issue 1:
By "i have not add my island name in to the web site"  I assume you mean that only All Islands exists in the calculator. "Restrict updates ..." means that only the island is updated that is currently viewed in the calculator (all other islands you created in the calculator are considered to be inactive). Maybe you find a better description for this option ...
I interpret your wish in the following: No matter which island is slected in the statistics menu, the same island is updated on the calculator site, i.e. it acts as if the calculator does not support multiple islands. Then, the problem arises when you switch between islands in the statistics menu that each screenshot will only hold information for a partial update. The consequence is that non-detected entries do not update the calculator, i.e. values are never set to zero -> the numbers in the calculator are a mixture of several islands.

Issue 2:
I choose to auto select the houses for two reasons:
1. the calculation is more accurate than with residents (latter one assumes that all houses are full)
2. most users would not know about this setting and still use the old, imprecise calculation

Just uncheck "Update houses count" to prevent switching to houses input.

**Comment by StingMcRay** [comment]
For my First Issue : I did not opened my "Statics View" to view my inhabitants, i mean this one 
![afbeelding](https://user-images.githubusercontent.com/18048706/70636431-cc05d480-1c35-11ea-933f-e4d87666b939.png)
If i not add the name on the calculator, all inhabitants counts stays on 0
After i added the name in the calculator, and selected it, then it shows, but that *as you self say* should not be needed to do that.
I will retest it again (i will delete the Islands name)

For my second issue : I will disable that, but i though the upper menu was for that.

**Comment by StingMcRay** [comment]
Because of the length of the following picture i will only place a link of it, so you can watch there
http://prntscr.com/q9ezvq
I removed the island name from the website (local one)
You will see what i mean 
I have restarted all (server > website > game)

**Comment by NiHoel** [comment]
The behavior is the same, no matter whether you read out the population from statistics or HUD. In both cases it distinguishes between global and island population (and also extracts the island name in the latter case).

**Comment by StingMcRay** [comment]
With other words : I must add the island names to the site ?

**Comment by NiHoel** [comment]
If you want to read out individual islands: yes (see above for the reasons)

Note: you can also read out the global population from HUD

**Comment by StingMcRay** [comment]
So : What is it that the normal Island Icon is not working?

**Comment by NiHoel** [comment]
Create island "Keinvakka" in calculator -> use popup "Island population" to read out population for "Keinvakka"

 use popup "Global population" to read out population for "All Islands" (why don't you just do that?)

It was never intended to be a long-term solution that "Island population" updates "All Islands". This just resulted from the delayed release of the statistics center (otherwise it would have been the way it currently is right when I released multi island support)

**Comment by NiHoel** [comment]
I recommend updating the calculator like this: https://raw.githubusercontent.com/NiHoel/Anno1800Calculator/master/CalculatorScreenshot.jpg

Just press CTRL+R

**Comment by StingMcRay** [comment]
I understand that, but what i liked (older one) is that when you hover above an island the data on website was also updated, now i need to make Island names in to the web site, if i like to monitor just 1 island, and not world wide inhabitants. 

Is there a possibility to add a choice ether work on World Wide Inhabitants (as all island tab) or as Only Island Inhabitants (as all islands tab), as i only build and make the needs for that island.
As the creating the Island names into the website can be an heavy thing (as copy name not seams to working), if you do an other new game (MP, Coop, alone)

**Comment by NiHoel** [comment]
You know that you can import / export all parameters when switching between games.

And it makes senese to rename each island to a well distinguishable and recognizable name. The only other **proper** way I see to conform your wish is to add an option "Disable multi island support".

I wonder why you did not experience issue #9.

**Comment by StingMcRay** [comment]
> The only other proper way I see to conform your wish is to add an option "Disable multi island support".

I'm very pleased if you could make that :)

The attention of #9 was indeed missed by me, however i have something else but can not make an issue of it yet, before i know what it is (*program exiting it self, when running other programs/websites* but i really need more information.)
