### ISSUE TITLE
Server missing 4 Icon Files

### ISSUE THREAD

**Issue by Gersdorff** [Dejauxvue/AnnoCalculatorServer#9]
After execute the Server.exe, it writes that 4 icons files could not load. These files are also missing into the matching folder.

![server_icon_fehlt](https://user-images.githubusercontent.com/58783912/70640941-1dfe2880-1c3d-11ea-8a6b-4ff73a1301e8.JPG)

**Comment by NiHoel** [comment]
Fixed, release updated.

**Comment by Gersdorff** [comment]
Thank you very much for the quick work
